name: CI
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps
      - name: Run tests
        run: |
          pytest -n auto --alluredir=allure-results
      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
      - name: Publish Allure Report to GitHub Pages
        uses: simple-elf/allure-report-action@v1.8
        if: github.ref == 'refs/heads/main'
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          subfolder: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
